[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "matprotlib"
version = "0.2.0"
authors = [
  { name="Tyson Tran", email="tyson26tran@gmail.com" },
]
description = "A clean and simple material property database."
readme = "README.md"
license = {text = "MIT License"}
requires-python = ">=3.7"
dependencies = [
    "numpy",
    "pandas",
    "streamlit"
]
[project.scripts]
matprotlib-ui = "matprotlib:launch_dashboard"
